### ISSUE TITLE
[2주차] Git 명렁어

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#10]
# 개요
1. Git 기본 명령어 종류
2. Commit 메시지 best practice 작성법
3. Reset 종류(hard, soft ... 등등)
4. Pull 차이(rebase, merge ... 등등)

**Comment by dbzoseh2rl** [comment]
## <1. Git 기본 명령어 종류>
- git init
   Git 저장소를 초기화합니다. 현재 디렉토리에 .git 디렉토리를 생성하여 Git의 저장소로 설정한다.
- git clone
  원격 저장소로부터 저장소를 복제한다.
- git add
  변경된 파일들을 스테이징 영역에 추가한다.
- git commit
  스테이징 영역에 있는 변경 사항을 로컬 저장소에 커밋한다.
- git status
  작업 디렉토리의 상태를 확인한다.
- git log
  커밋 로그를 확인한다..
- git pull
  원격 저장소로부터 변경 사항을 가져와 현재 브랜치를 업데이트한다.
- git push
  로컬 저장소의 변경 사항을 원격 저장소로 업로드한다.
- git branch
  브랜치 목록을 확인하거나 새로운 브랜치를 생성한다.
- git merge
  다른 브랜치로 이동하거나 특정 커밋으로 돌아간다.
- git remote
  원격 저장소를 관리한다.
- git fetch
  원격 저장소에서 최신 변경 사항을 로컬 저장소로 가져온다.
- git diff
  작업 디렉토리나 스테이징 영역과 최신 커밋 간의 차이를 확인한다.

## <2.Commit 메시지 best practice 작성법>
- 제목과 본문을 한 줄 띄워 분리하기
- 제목은 영문 기준 50자 이내로
- 제목 첫 글자를 대문자로
- 제목 끝에 . 금지
- 제목은 명령조로
- Github - 제목(이나 본문)에 이슈 번호 붙이기
- 본문은 영문 기준 72자마다 줄 바꾸기
- 본문은 어떻게보다 무엇을, 왜에 맞춰 작성하기
> 코드예시
```
type: Subject

body

footer
```
### - 타입종류
- feat : 새로운 기능 추가
- fix : 버그 수정
- docs : 문서 수정
- style : 코드 formatting, 세미콜론(;) 누락, 코드 변경이 없는 경우
- refactor : 코드 리팩터링
- test : 테스트 코드, 리팩터링 테스트 코드 추가(프로덕션 코드 변경 X)
- chore : 빌드 업무 수정, 패키지 매니저 수정(프로덕션 코드 변경 X)
- design : CSS 등 사용자 UI 디자인 변경
- comment : 필요한 주석 추가 및 변경
- rename : 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
- remove : 파일을 삭제하는 작업만 수행한 경우
- !BREAKING CHANGE : 커다란 API 변경의 경우
- !HOTFIX : 급하게 치명적인 버그를 고쳐야 하는 경우

## <3.Reset 종류>
- git reset --soft <commit>: 커밋은 취소되지만 변경된 파일은 스테이징 영역에 남아 있다.
  ex)  git reset --soft <commit_hash>
- git reset --mixed <commit>: 커밋은 취소되고, 변경된 파일은 작업 디렉토리에 보존되지만 스테이징 영역에서는 제거된다.
  ex)  git reset --mixed <commit_hash>
- git reset --hard <commit>: 커밋은 완전히 제거되며, 변경된 파일도 스테이징 영역에서 작업 디렉토리로 삭제된다.
  ex)  git reset --hard <commit_hash>
- git reset <commit> (mixed 생략): --mixed가 생략된 형태로, git reset <commit>과 동일하다.
  ex)  git reset <commit_hash>

## <4.Pull 차이>
- 기본적인 Pull: 원격 저장소에서 변경 사항을 가져와 현재 브랜치에 병합합니다. 이는 "Fetch + Merge"의 단축 명령이다.
  ex)  git pull
- Rebase :  git pull을 사용하면 원격 변경 사항을 가져와서 현재 브랜치에 Rebase할 수 있다.
  ex)  git pull --rebase
- Fetch만 수행: "Fetch + Merge"를 수행합니다. --no-merge 옵션을 사용하여 Fetch만 수행할 수 있다.
  ex) git pull --no-merge
- Rebase만 수행: 로컬 브랜치를 최신 원격 브랜치로 업데이트할 때 유용하다.
  ex) git pull --rebase origin <branch_name>
- Pull 하기 전에 Fetch만 수행: 원격 저장소에서 변경 사항을 미리 가져온 후, 이후에 git pull을 실행할 수 있다.
  ex) git fetch
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;git pull

**Comment by Paransaik** [comment]
1. `Git 저장소를 초기화합니다.` 다른 곳은 다 반말인데 여기는 존댓말이네요.
2. `커밋 로그를 확인한다..` 오타


잘 조사하였는데 실제 commit message 작성 시 조사한 내용을 바탕으로 작성 바랍니다

저희는 해당 조사 내역을 따르 되, body를 짧게 적고 footer를 생략하겠습니다.

**Comment by dbzoseh2rl** [comment]
오류사항 수정했고,  body를 짧게 적고 footer를 생략 하는내용 확인했습니다.
