### ISSUE TITLE
[2주차] Spring Directory Structure

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#11]
# 개요
1. Spring Directory Structure 종류 조사
2. 좋은 Spring Directory Structure 설계 방법
3. 우리 프로젝트에 어떤 Structure 를 적용시킬 것인가?

**Comment by Paransaik** [comment]
[참고 자료](https://cheese10yun.github.io/spring-guide-directory/)

**Comment by dbzoseh2rl** [comment]
## <1. Spring Directory Structure 종류>
### ▶  계층형
  - 각 계층을 대표하는 디렉터리를 기준으로 코드들이 구성한다.
  - 해당 프로젝트에 이해가 상대적으로 낮아도 전체적인 구조를 빠르게 파악할 수 있다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/99e9e54d-d333-47dd-a69d-5aff0b6e732a)
#### ↘장점
- 해당 프로젝트에 이해가 상대적으로 낮아도 전체적인 구조를 빠르게 파악할 수 있다.
#### ↘단점
- 디렉토리에 클래스들이 너무 많이 모이게 됨.
-  모듈 단위로 분리 시 어려움이 있음.
 
### ▶ 도메인형
- 도메인 디렉터리 기준으로 코드를 구성한다.
- 관련된 코드들이 응집해 있는 장점이 있다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/31d4f6ea-33ea-410e-8e2e-32256785331c)
#### ↘장점
- 관련된 코드들이 응집해 있음.
- 모듈 단위로 분리할 때 유리함.
#### ↘단점
- 프로젝트에 대한 이해도가 낮을 경우 전체적인 구조를 파악하기 어려움.
- 개발자의 성향에 따라 도메인을 구분하는 기준이 다를 수 있고, 
   내 예상과 다른 패키지에 존재하는 경우 관련 코드를 찾기 어려움.

## <2. 좋은 Spring Directory Structure 설계 방법> 
- Layered Architecture 구조: 일반적으로 Spring 프로젝트는 계층 구조를 따릅니다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/29b7e6c2-b677-4a55-b30d-cceb6568d514)
- 모듈화:  프로젝트를 기능별 또는 도메인별로 모듈화하여 구성하면 유지보수와 확장성이 향상된다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/a5ab4269-4207-4912-9b68-7628286de6f6)
- 패키지 네이밍 규칙:  패키지 네이밍 규칙을 명확하게 정의하여 가독성을 높인다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/9b937e24-e83d-4940-85e9-4367dbb0c0ac)
- 리소스 디렉토리 구성: src/main/resources 디렉토리는 설정 파일, 정적 자원, 템플릿 등을 포함한다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/05b11373-e1da-4eb6-81f4-ce19e879a5f8)
- 테스트 디렉토리 구성: 테스트 코드는 src/test/java 디렉토리에 위치하며, 테스트 리소스는 src/test/resources에 위치한다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/9ff48e76-a267-41f2-8669-6b084fce6a79)
- 패키지 분리: 컨트롤러, 서비스, 리포지토리 등 각 계층의 코드를 별도의 패키지로 분리한다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/25ff3064-7a29-4948-a1c1-568cec603574)

## <3. 우리 프로젝트에 어떤 Structure 를 적용시킬 것인가>
계층형 같은 경우 Controller, Service 등에 너무 많은 클래스들이 밀집하게 되어서,  길게 나열되어
프로젝트 전체적인 구조는  빠르게 파악할 수 있지만 많아질수록 파악이 힘들어질 것이기때문에
추후에 프로젝트에서 추가하거나 업데이트를 하게 된다고 가정했을때 어려움이 있을거같아
도메인형을 적용시킬 것이다.

@ 참고자료: https://velog.io/@haron/Spring-Project-Structure

**Comment by Paransaik** [comment]
LGTM~
