### ISSUE TITLE
[2주차] Spring Boot build.grade setting & Create Folder

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#12]
# 개요
1. build.gradle file setting 공부하기
2. 설계를 바탕으로 Folder를 생성

**Comment by dbzoseh2rl** [comment]
## <1. build.gradle file setting 공부하기>
- build.grade의 기본 file 구성은 아래와 같다.
```
// apply 키워드를 사용하여 플러그인 적용
apply plugin: 'java'

// 프로젝트의 그룹 및 버전 설정
group 'com.example'
version '1.0-SNAPSHOT'

// Java 플러그인의 설정
java {
    // 소스 및 리소스 디렉토리 설정
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    // 소스 세트 설정 (예: src/main/java, src/test/java)
    main {
        java.srcDirs = ['src/main/java']
        resources.srcDirs = ['src/main/resources']
    }
    test {
        java.srcDirs = ['src/test/java']
        resources.srcDirs = ['src/test/resources']
    }
}

// 의존성 관리
dependencies {
    // 외부 라이브러리 의존성 추가
    implementation 'group:artifact:version'
    // 테스트 의존성 추가
    testImplementation 'junit:junit:4.12'
}
```

## <2. 설계를 바탕으로 Folder를 생성>
- 설계를 바탕으로 buil.gradle 파일을 생성해서 코드를 작성 하였다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/911a3444-093d-4ad2-83a0-03ec75a3e100)

**Comment by Paransaik** [comment]
실제 Folder 작성 시 아래 이미지와 같이 '└', '─', '┣'와 같은 특수문자(ㅂ + 한자)를 사용하여 한번 그려보세요.

그린 후 왜 그런 구조로 가져갔는지 설명 추가해주세요!

**Comment by dbzoseh2rl** [comment]
폴더 구조를 그리고 설명 추가하였습니다!

**Comment by Paransaik** [comment]
이미지 패키지명 바꾸고 다른 것도 신경써서 다시 사진 올려주세요~

폴더 구조는 잘 그려주셨는데 들여쓰기가 안맞네요! 수정 부탁드려요.
