### ISSUE TITLE
[3주차] Spring vs Spring Boot

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#14]
# 개요
1.  Spring History(등장 배경, 짧게)
2.  Spring과 Spring Boot 차이점
  2-1. Spring Boot 만의 장점

**Comment by dbzoseh2rl** [comment]
## <1. Spring History>
### - 등장배경
- 복잡한 기업 환경: 자바 기반의 기업급 애플리케이션 개발은 복잡한 구조와 많은 기술적 
   도전 과제를 포함하고 있었다. 이에 대응하기 위해 강력하면서도 유연한 프레임워크가 필요했다. 
- 경량 프레임워크 수요 증가: 경량하면서도 강력한 프레임워크에 대한 
  수요가 증가하였고,  이에 따라 스프링 프레임워크가 등장하게 되었다.
- 2002년: 자바 개발자인 Rod Johnson이 스프링 프레임워크의 초안인
  "Spring Framework"를 출판한 책으로 처음 소개했다. 
- 2004년: 스프링 프레임워크 1.0 버전이 공식적으로 발표되었다. 
   이 버전에서는 제어의 역전(IoC)과 의존성 주입(DI) 같은 핵심 컨셉이 소개되었다.

## <2. Spring과 Spring Boot 차이점>
|비고|Spring|Spring Boot|
|---|---|---|
|프로젝트<br> 설정 및 구성|- 설정이 복잡하고 초기 구성이 필요하다<br>- XML 파일이나 Java Config를 통해 설정을<br>&nbsp;&nbsp;작성해야 한다. |- "초기화 코드" 원칙에 따라 많은 설정을<br> &nbsp;&nbsp;자동으로 처리한다. <br>- 내장된 디폴트 설정을 사용하면 추가적인  <br>&nbsp;&nbsp;구성이나XML 파일 없이도 빠르게 개발을 <br>&nbsp;&nbsp;시작할 수 있다.|
|의존성<br> 관리|- 스프링에서는 각 라이브러리의 버전을 <br>&nbsp;&nbsp;수동으로 관리해야 한다. <br>- Maven이나 Gradle과 같은 빌드 도구를<br> &nbsp;&nbsp;통해 의존성을 명시적으로 설정해야 한다.|- 자동으로 버전을 관리해주는 스타터 <br>&nbsp;&nbsp;패키지를 제공한다. <br>- 특정 기능에 필요한 의존성들을 <br>&nbsp;&nbsp;쉽게 추가할 수 있다.|
|내장 서버|- 스프링에서는 기본적으로 서블릿 컨테이너 <br> &nbsp;&nbsp;(Tomcat등)를 따로 설정해주어야 한다.|- 별도의 서버 설정 없이도 단독으로 실행  <br>&nbsp;&nbsp;가능하며, 필요에 따라 다른 내장 서버로  <br>&nbsp;&nbsp;변경할 수 있다|
|편의성 <br>및 간결성|- 스프링은 유연성과 확장성을 중시하는 <br>&nbsp;&nbsp;대신 초기 설정이나 일부 기능에서<br>&nbsp;&nbsp;복잡할 수 있다.|- 개발자들은 더 적은 노력으로 빠르게 개발에 <br>&nbsp;&nbsp;집중할 수 있다.|

## <3. Spring Boot 만의 장점>
- 빠른 개발 및 프로토타이핑
- 스타터(Starter) 패키지
- 자동 구성(Auto-Configuration)
- 내장 서버(Embedded Server)
- 의존성 관리 자동화
- 통합된 보안 기능
- 간결한 설정 및 생산성 향상

@ 참고자료: https://www.inflearn.com/blogs/3315

**Comment by Paransaik** [comment]
잘 조사하였네요~ 짝짝짝
