### ISSUE TITLE
[3주차] DI

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#16]
#개요
1. Spring에서 DI란?
2. 예시 코드
3. DI 3가지 각 장단점
4. 예시 코드

**Comment by dbzoseh2rl** [comment]
## <1. Spring에서 DI란>
- DI란 외부에서 두 객체 간의 관계를 결정해주는 디자인 패턴으로, 인터페이스를 사이에 둬서 클래스 레벨에서는 
   의존관계가 고정되지 않도록 하고 런타임 시에 관계를 동적으로 주입하여 유연성을 확보하고 결합도를 낮출 수 있게 해줌.

## <2. 예시코드>
- 의존성 주입(Dependency Injection)이 필요한 코드
```
public class Store {

    private Pencil pencil;

    public Store() {
        this.pencil = new Pencil();
    }

}
```
위 코드의 문제점으로
- 두 클래스가 강하게 결합되어 있다.
- 객체들 간의 관계가 아니라 클래스 간의 관계가 맺어짐.
위의 문제점을 고치기 위해서는 아래의 코드와 같이 수정해야 한다. 
```
public interface Product {

}

public class Pencil implements Product {

}
```

**Comment by Paransaik** [comment]
https://mangkyu.tistory.com/125
