### ISSUE TITLE
[1주차] 게시판 DB설계

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#2]
# 개요
1. MySQL을 사용하여 아래 요구사항을 반영할 수 있는 Table을 설계할 것
2. [draw.io](https://draw.io/)를 이용한 Table ERD 작성

> 게시한 ID(기본키)를 통한 CRUD
> 테이블 설계 방법 및 네이밍 컨벤션을 조사 후 테이블 설계

**Comment by dbzoseh2rl** [comment]
Table ERD링크 = https://drive.google.com/file/d/1nUCcKIaVbGLnonQI2wWKf48v7PBlSM98/view?usp=sharing

CREATE DATABASE test;
USE test;
CREATE TABLE 회원(
	회원ID INT(20) primary key not null, 
	password VARCHAR(30) not null, 
	name VARCHAR(10) not null, 
	phonenumber VARCHAR(20) not null, 
	grade VARCHAR(10) not null,
	email VARCHAR(30) not null, 
	adress VARCHAR(30) not null
);

CREATE TABLE 주문(
	주문ID INT(20) primary key not null, 
	회원ID INT(20) not null, 
	통합가격  INT(10) not null, 
	요청사항 VARCHAR(30) not null, 
	주문상태 VARCHAR(10) not null,
	결제수단 VARCHAR(10) not null
);

CREATE TABLE 가게(
	가게ID INT(20) primary key not null,
	가게이름 VARCHAR(20) not null, 
	배달_포장 VARCHAR(10) not null,
	주소 VARCHAR(30) not null,
	전화번호 VARCHAR(30) not null,
	소개글 VARCHAR(30)  null,
	음식카테고리 VARCHAR(30) not null,
	배달팁 INT(10) not null,
	찜수 INT(10)  not null,
	리뷰수 INT(10)  not null,
	휴무일 VARCHAR(30) null,
	오픈시간 VARCHAR(30) not null,
	마감시간 VARCHAR(30) not null,
	최소주문금액 int(10) not null
);

CREATE TABLE 장바구니(
	장바구니ID INT(20) primary key not null, 
	회원ID INT(20) not null, 
	가게ID INT(20) not null, 
	메뉴ID  INT(20) not null, 
	수량 INT(10) not null
);

CREATE TABLE 메뉴(
	메뉴ID INT(20) primary key not null, 
	카테고리 VARCHAR(20) not null,
	메뉴명 VARCHAR(20) not null,
	가격 INT(10) not null
);

**Comment by Paransaik** [comment]
1. `drop table board;` 명령어 따로 놉니다
2. 테이블 필드에 조회수가 들어가면 좋을 거 같네요
3. 테이블 명은 대문자, 복수형으로 지정 바랍니다 => BOARDS
4. 테이블 필드 명 중 기본키는 스네이크 표기법인데 userName은 카멜 케이스네요 통일 부탁드립니다 => 보통 스네이크 사용
5. NOT NULL은 공백으로 띄워주세요
6. updatedate 는 필요 없어서 제거 바랍니다


작성에 참고하신 문서 있으시면 공유 부탁드립니다^^
없으면 인터넷에서 좋은 DB 설계법 참고 후 작성 및 공유 바랍니다

**Comment by dbzoseh2rl** [comment]
위의 수정사항 반영해서 수정하였습니다!

**Comment by Paransaik** [comment]
post + date 이므로 post_date가 좋을 거 같아요.

근데, erd는 안바꾸셨네요 ^^;
int, varchar와 같은 자료형은 대문자가 보기 좋은 것 같습니다.
또한, DDL과 `primary key`도 예약어이므로 대문자 부탁드립니다.

**Comment by dbzoseh2rl** [comment]
수정완료 하였습니다!

**Comment by Paransaik** [comment]
제가 생각해 봤는데 저희는 간단하게 보드만 구현기에 user_name를 제거하는 게 좋을 거 같고,
views은 "조회 수"이니 view_count 혹은 view_cnt가 나아 보입니다.

보통 view_count, view_cnt이 둘의 차이는 DB를 설계하기전에 데이터 사전이란 것을 만드는데 검색 해보시고,
어떤 게 좋은지 생각해보시길 바랍니다.

수정 후 Close 해주세요~

**Comment by Paransaik** [comment]
DB erd와 설계 매핑 필요
