### ISSUE TITLE
[1주차] Gradle vs Maven

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#3]
# 개요
1. Gradle vs Maven이 뭔지 알 것
2. 둘이 변환하는 방법에 대해 조사할 것
3. Markdown 문법으로 여기에 정리할 것

**Comment by dbzoseh2rl** [comment]
##  1. Gradle vs Maven
* Gradle
    Groovy 기반으로 한 BUILD TOOL이다.
    Gradle은 거의 모든 타입의 소프트웨어를 빌드할 수 있는 유연함을 가진다.
    - Gradle의 특징:
        - Ant(빌드 도구) 와 Maven의 장점을 모아 만들었다.
        - 의존성 관리를 위한 다양한 방법을 제공한다.
        - Maven의 pom.xml을 Gradle 용으로 변환할 수 있어 Maven 라이브러리를 모두 그대로 가져다 사용할 수 있다
        - Gradle Wrapper를 이용하면 Gadle이 설치되지 않은 시스템에서도 프로젝트를 빌드할 수 있다.
        - Groovy가 자바 문법과 유사해 자바 개발자가 쉽게 익힐 수 있다.
     - radle의 빌드가 빠른이유
        - 점진적 빌드(Incremental Build)
           점진적 빌드란, 이미 빌드된 파일말고 변경된 파일만 빌드하는 것을 말한다.
빌드 속도가 빠른 가장 큰 이유라고 할 수 있다.
        - 빌드 캐시(Build cache)
           먼저 빌드된 파일이 있을 경우, 빌드 캐시를 이용해 해당 내용을 공유한다.
이로 인해 같은 파일이 다시 빌드되지 않아 빌드 시간이 줄어든다.

* Maven
   Maven은 지금까지 애플리케이션을 개발하기 위해 반복적으로 진행해왔던 작업들을 지원하기 위하여 등장한 도구입니다.
Maven을 사용하면 빌드(Build), 패키징, 문서화, 테스트와 테스트 리포팅, git, 의존성관리, svn등과 같은 형상관리서버와 연동(SCMs), 배포 등의 작업을 손쉽게 할 수 있습니다.
   - Maven특징:
      - XML 기반으로 작성된다.
      - Gradle에 비해 어렵다.
      - 라이브러리의 dependency가 늘어나면 매우 복잡도가 높아진다.
  
***
## 2.둘의변환방법
* Gradle -> Maven
   - 프로젝트 폴더 우클릭 - Add Framework Support - Maven클릭
* Maven -> Gradle
   - 프로젝트 폴더(pom.xml이 있는 곳으로 이동) -> gradle init --type pom -> Select groovy(1번)

**Comment by Paransaik** [comment]
1. Gradle 특징 중 "~만듦, 했음, 됨"으로 끝나는 문장과 "수 있다."으로 끝나는 문장 일관성 있게 통일해 주세요!
2. Maven에서 `연동(SCMs), 배포` 부분 들여쓰기가 들어갔네요.

**Comment by dbzoseh2rl** [comment]
위의 수정사항 반영해서 수정하였습니다!

**Comment by Paransaik** [comment]
LGTM~
