### ISSUE TITLE
[1주차] Markdown

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#4]
# 개요
1. Markdown이 뭔지 조사할 것
2. Markdown 문법에 어떤 것들이 있는지 조사할 것

**Comment by dbzoseh2rl** [comment]
# 1. Markdown 언어란?
- Markdown은 텍스트 기반의 마크업언어이다. README 파일이나 온라인 문서,
혹은 일반 텍스트 편집기로 문서 양식을 편집할 때 쓰입니다.
- 마크다운을 이용해 작성된 문서는 쉽게 HTML등 다른 문서형태로 변환이 가능합니다.
# 2. Markdown 문법에는 어떤 것들이 있는가?
* `#` 의갯수에따라 태그를 설정할 수 있습니다.
   - `#` This is a H1
   - `##` This is a H2
   - `###` This is a H3
   - `####` This is a H4
   - `#####` This is a H5
   - `######` This is a H6 <br></br>
* 강조
   - 이텔릭체는 `*`별표(asterisks)`*` 혹은 _언더바(underscore)_를 사용할 수 있습니다.
   - 두껍게는 `**`별표(asterisks)`**` 혹은 __언더바(underscore)__를 사용할 수 있습니다.   
   - **_이텔릭체_와 두껍게**를 같이 사용할 수 있습니다.
   - 취소선은 ~~물결표시(tilde)~~를  사용할 수 있습니다. 
   - <u>밑줄</u>은 `<u></u>`를  사용할 수 있습니다.<br></br>
* 인용된 글자를 표현하고자 할 때, `>`기호를  사용할 수 있습니다.
   - > This is a blockqute. <br></br>
* 순서가 필요한 목록에 대해서 사용할 수 있습니다.  
   - `1. 순서`
   - `2. 순서`
   - `3. 순서`<br></br>
* 순서가 없는 목록(Bullet Lists)은 *, +, - 기호를 사용하여, 계층이 필요한 경우에는 들여쓰기를 하면 됩니다. 
   - `* 빨강`
         `* 녹색`
              `* 파랑`

    - `+ 빨강`
         `+ 녹색`
             `+ 파랑`

    - ` - 빨강`
          `- 녹색`
              `- 파랑`
<br></br>
* 코드블럭
   - `<pre><code>{code}</code></pre>` 사용하는 방식
   - ```을 사용하는 방식
<br></br>
* 수평선
- 아래의 5가지 방법 모두 수평선을 만듭니다.
   `* * *`
   `***`
   `*****`
   `- - -`
   `---------------------------------------`
<br></br>
* 링크연결
   - 일반적인 URL 혹은 이메일주소인 경우 적절한 형식으로 링크를 형성합니다.
      외부링크: <http://example.com/><br></br>
* 이미지 사용 
   - `<img src="/path/to/img.jpg" width="450px" height="300px" title="px(픽셀) 크기 설정" alt="RubberDuck"></img><br/>`
   - `<img src="/path/to/img.jpg" width="40%" height="30%" title="px(픽셀) 크기 설정" alt="RubberDuck"></img>`

**Comment by Paransaik** [comment]
코드블럭과 수평선 사이에 다른 거와 달리 공백이 너무 많은 거 같은데 일관성 있게 양식 한번 맞춰주세요~

**Comment by dbzoseh2rl** [comment]
위의 수정사항 반영해서 수정하였습니다!

**Comment by Paransaik** [comment]
LGTM~
