### ISSUE TITLE
[1주차] Lombok

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#5]
# 개요
1. Lombok 개념 정리할 것
2. 어노테이션 개념 정리할 것
3. 사용하면 안되는 어노테이션 정리할 것

**Comment by dbzoseh2rl** [comment]
# 1. Lombok이란?
- Java의 라이브러리로 반복되는 메서드를 Anntation을 사용해 자동으로 작성해주는 아주 편리한 라이브러리입니다.
Lombok을 이용한다면 어노테이션을 이용하는 것 만으로 자동으로 Getter, Setter, 생성자 등의 코드를 작성해줘 
번거로운 과정을 제거해줍니다.

# 2. 어노테이션 개념
- 어노테이션은 다른 프로그램에게 유용한 정보를 제공하기 위해 사용되는 것으로 주석과 같은 의미를 가진다.

- 어노테이션의 역할
   - 컴파일러에게 문법 에러를 체크하도록 정보를 제공한다.
   - 프로그램을 빌드할 때 코드를 자동으로 생성할 수 있도록 정보를 제공한다.
   - 런타임에 특정 기능을 실행하도록 정보를 제공한다.
   - `@`를 사용하여 작성하며, 해당 타겟에 대한 동작을 수행하는 프로그램 외에는 다른 프로그램에게 영향을 주지 않는다.

- 종류
   -@Override
       컴파일러에게 메서드를 오버라이딩하는 것이라고 알린다.
   - @Deprecated
       앞으로 사용하지 않을 대상임을 알린다.
   - @FunctionalInterface
       함수형 인터페이스라는 것을 알린다.
   - @SuppressWarning
       컴파일러가 경고 메시지를 나타내지 않는다.
   - @Setter
       Class 모든 필드의 Setter method를 생성해줍니다.
   - @Getter
       Class 모든 필드의 Getter method를 생성해줍니다.
   - @AllArgsConstructor
       Class 모든 필드 값을 파라미터로 받는 생성자를 추가합니다.
   - @NoArgsConstructor
       Class 기본 생성자를 자동으로 추가해줍니다.
   - @ToString
       Class 모든 필드의 toString method를 생성한다.

- 사용예시
* 일반적인 클래스
```
public class Student {
    private int studentNum;
    private String name;
    private int age;

    public int getStudentNum() {
        return studentNum;
    }

    public void setStudentNum(int studentNum) {
        this.studentNum = studentNum;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
```

* Lombok클래스
```
import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class Student {
    private int studentNum;
    private String name;
    private int age;
}
```
# 3. 사용하면 안되는 어노테이션
- @AllArgsConstructor
   - 클래스에 존재하는 모든 필드에 대한 생성자를 자동으로 생성한다.
   - 예로 들어, 두 개의 같은 타입 인스턴스 멤버를 선언한 상황에서 개발자가 선언된 인스턴스 멤버의 순서를 바꾸면,
개발자도 인식하지 못하는 사이에 lombok이 생성자의 파라미터 순서를 필드 선언 순서에 따라 변경하게 된다.
이때, IDE가 제공해주는 리팩토링은 전혀 동작하지 않고, 두 필드가 동일 타입이기 때문에 기존 소스에서도 오류가
발생하지 않아 아무런 문제없이 동작하는 것으로 보이지만, 실제로 입력된 값이 바뀌어 들어가는 상황이 발생한다.

- @Data
   - @Data = @RequiredArgsConstructor + @Getter + @Setter + @ToString + @EqualsAndHashCode
각 annotation의 주의사항을 모두 포함한다.
   - 예를 들어, 객체를 Set에 저장한 뒤 필드 값을 변경하면 hashCode가 변경되면서이전에 저장한 객체를 찾을 수 없는 
문제가 발생한다.
   - @Data 대신, @Getter, @Setter, @ToString으로 명시하는 것을 권장한다.

- @NoArgsConstructor
   - 파라미터가 없는 생성자를 생성한다.
   - 사용 시 주의 사항
          필드들이 final로 생성되어 있는 경우에는 필드를 초기화할 수 없기 때문에 생성자를 만들 수 없고 에러가 발생한다. 
→ @NoArgsConstructor(force=true) 옵션을 이용해 final 필드를 강제 초기화 시켜 생성자를 만들 수 있다.
   - @Nonnull 같이 필드에 제약조건이 설정되어 있는 경우, 추후 초기화를 진행하기 전까지 생성자 내 null-check 로직이 생성되지 않는다.

- @Builder
   - @Builder를 사용하면 객체 생성이 명확해진다.
   -  가급적 클래스 보다는 직접 만든 생성자 혹은 static 객체 생성 메소드에 붙이는 것을 권장한다.
   - @Builder를 붙이면 파라미터 순서가 아닌 이름으로 값을 설정하기 때문에 리팩토링에 유연하게 대응할 수 있고,
 필드 순서를 변경해도 문제가 없다.

**Comment by Paransaik** [comment]
해당 파일 어노테이션 대소문자 구분 필요.
