### ISSUE TITLE
[1주차] Spring Boot 실행하기

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#6]
# 개요
1. Spring Boot Template 만들기
2. 아래 Branch 관리 전략에 맞게 Branch 생성 후 작업
     - https://github.com/ParansaikStudy/LDK-SpringBase/issues/1
3. Gradle 사용할 것
    - Gradle 에 Dependency 추가할 때 버전 명시할 것
4. Lombok 추가할 것
5. PR 하기 전 New Branch -> Develop Branch 확인
6. 그 외에 추가해야 할 게 뭐가 있는지 고민해보기

**Comment by Paransaik** [comment]
해당 내용 실습 한 거 여기에 정리해주세요

**Comment by dbzoseh2rl** [comment]
1. Spring Boot Template 만들기
SpringBase-LDK Template를 만들었습니다. 
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/49bbf4d5-d902-48c0-a480-d8275fa52628)

2. Branch생성 후 작업 
Branch 전략에 맞게 master branch를 만들어서 하위에 develop2을 추가해 주었습니다. 
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/f84e22b1-cb8e-49de-abed-24c0e54baf6e)


3. Gradle 사용
build.gradle에서 사용할 의존성을 추가하고, java version 및 springframework version을 맞추었습니다.
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/a885d03f-aa0b-4bd2-99b3-97af9735fad7)

4. Lombok 추가
Lombok을 다운받아 추가해 주었습니다. 
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/943d1f49-984e-4ff2-892d-bf1e2f5eb2e6)

5. New Branch -> Develop Branch
PR하기전 Branch확인을 완료하였습니다. 
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/4b163e49-5266-4b6b-afb5-86505a7239b9)

**Comment by Paransaik** [comment]
1. Application 이름이 LankupApplication.java네요 해당 java file도 수정해주셔야 합니다.
2. 해당 Project가 왜 `https://github.com/ParansaikStudy/LDK-SpringBase` 여기에 없죠?...
3. brach 전략은 feature/{issue-number}-{issue-name}을 따르기로 했습니다. 수정부탁드려요
4. 작업하시는 내용은 ParansaikStudy내에 Repo를 만들어서 하시는 겁니다!!

해당 내용이 이해하기 어렵다면 질문 부탁드려요!

결론: 다시하셔야 됨

**Comment by dbzoseh2rl** [comment]
1.  파일이름 수정하였습니다.
2.  해당 파일 https://github.com/ParansaikStudy/LDK-SpringBase에 업로드 하였습니다. 
3. brach 전략에 맞게 수정하였습니다. 
4. Repo를 만들었습니다.

**Comment by Paransaik** [comment]
해당 내용 다시 확인 부탁드립니다.

1. 패키지명 변경
2. gradle에 group 명 변경
3. 브랜치 명에 # 뺄 것(브랜치명 수정 가능)
4. merge를 하면 안되고 PR을 날려야 됨(PR 수락 시 자동 머지)
