### ISSUE TITLE
[2주차] Properties vs YML

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#7]
# 개요
1. properties와 yml의 개념
2. 각각의 장단점
3. 각각 어디에 사용하면 좋은지?
4. 서로 변환 방법

**Comment by dbzoseh2rl** [comment]
## ▶ 개요 
1. [Properties](#1-properties)와 [Yml](#1-yml)의 개념
2. [각각의 장단점](#1-각각의-장단점)
3. [각각의 좋은 사용처](#1-각각의-좋은-사용처)
4. [서로 변환 방법](#1-서로-변환-방법)

## 1. Propertis와 Yml의 개념 
- Properties : 주로 Java 프로그램에서 구성 속성을 정의하는 데 사용되고,  
  &emsp;&emsp;&emsp;&emsp;&emsp;키와 값은 간단하게 '='로 구분됨.
  > -  example code 
    database.url=jdbc:mysql://localhost:3306/mydatabase
    database.username=myuser
    database.password=mypassword
- Yml :  사람이 읽기 쉽고 작성하기 쉬운 형식으로 데이터를 나타냄. 
           &emsp;&emsp;들여쓰기를 통해 계층 구조를 나타내며, 리스트와 맵을 지원함. 
           &emsp;&emsp;다양한 프로그래밍 언어에서 설정 파일, 데이터 직렬화 및 다양한 
           &emsp;&emsp;구성 요소에서 사용됨
  > -  example code 
         database:
         &emsp;url: jdbc:mysql://localhost:3306/mydatabase
         &emsp;username: myuser
         &emsp;password: mypassword

## 2. 각각의 장단점 
-  Properties
   - 장점: 
     - 간단하고 직관적
     - Java와의 호환성 
   - 단점:
     - 계층 구조 미지원
     - 가독성 부족
- Yml
  - 장점: 
     - 가독성 및 작성 용이함
     - 다양한 데이터 유형 지원 
  - 단점:
     - 강력한 기능의 남용
     - 몇몇 언어에서 지원이 덜 될 수 있음

## 3. 각각의 좋은 사용처
- Properties
   - Java 프로퍼티 파일
   - 간단하고 직관적인 설정이 필요한 경우
   - 소규모 프로젝트나 특정 설정이 필요한 경우
   - 간단한 설정이 필요한 경우나 Java 환경에서 작업할 때
- Yml
   - 복잡한 데이터 구조의 설정 파일
   - 다양한 프로그램 간의 데이터 전송에 사용
   - 개발자가 읽기 쉽고 작성하기 쉬운 형식
   - 잡한 데이터 구조, 계층 구조, 또는 가독성이 중요한 경우

## 4. 서로 변환 방법
-  rename으로 이름만 바꿔주면 된다. 
-  또 다른 방법으로는 (http://mageddo.com/tools/yaml-converter )사이트로가서
   변경해주는 방법도 있다

**Comment by Paransaik** [comment]
개요에 하이퍼링크는 왜 거신지 궁금하네요~ 
바로가기 구현하신 거 같은데 정상작동 안합니다.
확인 부탁드려요~

**Comment by dbzoseh2rl** [comment]
Markdown에서 단어 위치로 이동하는 것은 HTML의 앵커 태그를 사용하여 가능하다고 하여서 제거하였습니다.

**Comment by Paransaik** [comment]
각각의 장단점 같은 경우는 문장이 짧고 비교하기 쉽게 table을 이용해서 나타내면 좋을 거 같아요. 
한번 수정해보세요

**Comment by dbzoseh2rl** [comment]
수정 완료  하였고, table을 사용해보니 다음부터 문장이짧고 비교해야할때는table을 
사용하면 가독성이 더 좋을것 같네요!  좋은정보 감사합니다 :)
