### ISSUE TITLE
[2주차] Dto vs Entity

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#8]
# 개요
1. Dto와 Entity의 개념
2. 둘이 어떨 때 쓰는지?
3. 이번 프로젝트에 어떻게 적용할지 시뮬레이션 하기

**Comment by dbzoseh2rl** [comment]
## <1. Dto와 Entity의 개념>
### ▶ Dto
- DTO(Data Transfer Object)는 데이터 전송(이동) 객체(Java Beans)라는 의미를 갖는다.
- DTO는 주로 비동기 처리를 할 때 사용하고, DTO는 계층간 데이터 교환을 위한 객체이다.
### ▶Entity
- Entity 클래스는 실제 DB 테이블과 매핑되는 핵심 클래스로, 데이터베이스의 테이블에 존재하는 컬럼들을 필드로 
  가지는 객체이다.
- Entity는 데이터베이스 영속성(persistent)의 목적으로 사용되는 객체이며, 때문에 요청(Request)이나 응답(Response) 값을 
  전달하는 클래스로 사용하는 것은 좋지 않다.
- 많은 서비스 클래스와 비즈니스 로직들이 Entity 클래스를 기준으로 동작하기 때문에 Entity 클래스가 변경되면 여러 클래스에 영향을 줄 수 있다.

## <2. 둘의 사용처>
### ▶ Dto 
- 주로 데이터 전송을 위한 객체로 사용됩니다. 엔터티로부터 필요한 데이터만을 추출하거나, 여러 엔터티에서 
  필요한 정보를 모아서 전달할 때 사용됨.
- 주로 네트워크 통신이나 다른 계층 간 데이터 전송 시에 사용됩니다. 엔터티의 내부 구조를 감추고 필요한 
  정보만을 전달하는 데 유용함.
### ▶Entity
- 엔터티는 데이터베이스에서 식별 가능한 개체를 나타냄. 주로 데이터베이스 테이블과 매핑되는 객체로 생각할 수 있다.
- 엔터티는 비즈니스 도메인의 핵심 개념을 나타내며, 데이터베이스에서 상태를 유지하고 데이터를 영속적으로 저장함.

※ Entity와 DTO를 분리해서 관리해야 하는 이유
 - DB와 View 사이의 역할을 철저히 분리하기 위함이다.
 - Entity 클래스는 실제 테이블과 매핑되어 만일 변경되기 된다면 다른 클래스에 영향을 끼치고
    DTO 클래스는 View와 통신하며 자주 변경되므로 분리해주어야 한다. (Entity 클래스 보호)

## 3. 이번 프로젝트에 어떻게 적용할지 시뮬레이션 하기
- 이번 프로젝트에서 board_id , username, title, content, post_date, views를 사용한 Entity를 만들고
   Dto의 경우는 Entity로 정한 것들의 값이 실제로 값이 전달되고 데이터 통신이 잘되게 설계할 예정입니다.

**Comment by Paransaik** [comment]
잘 조사하였네요

참고자료 오타있습니다.
수정 후 Close 부탁드려요~
