### ISSUE TITLE
[2주차] REST API

### ISSUE THREAD

**Issue by Paransaik** [ParansaikStudy/LDK-SpringBase#9]
# 개요
1. REST API 란?
2. 좋은 REST API  설계 방법
3. 현재 프로젝트 REST API 설계 하기

**Comment by dbzoseh2rl** [comment]
## <1. Rest API 란>
- REST API(Representational State Transfer API)는 웹 서비스를 구축하는 데 사용되는 소프트웨어 아키텍처 스타일 중 하나이다. 
  REST는 자원을 표현하고 상태를 전송하기 위한 아키텍처로, 웹에서 가장 널리 사용되는 방식 중 하나이다. 
  REST API는 HTTP 프로토콜을 기반으로 하며, 클라이언트와 서버 간의 통신을 단순하게 만들어주는 특징이 있다.

## <2. 좋은 Rest Api 설계 방법>
- 명확하고 일관된 URI 구조:
   URI는 간결하고 직관적이어야 한다.
- HTTP 메서드 활용:
  각 리소스에 대한 적절한 HTTP 메서드를 사용한다.
- 표현 형식:
  주로 JSON 혹은 XML을 사용하며, 클라이언트와 서버 간에 통신하는 데이터 형식은 일관되어야 한다.
- 상태 관리 (State Management):
  서버는 클라이언트의 상태를 저장하지 않도록 설계되어야 한다.
- 보안:
  SSL을 통한 암호화를 사용하여 보안을 강화한다.
- 성능 최적화:
  필요한 경우 캐싱을 활용하여 성능을 최적화한다.

## <3. 현재 프로젝트 Rest Api 설계해오기>
현재 프로젝트에서 Rest Api는 아래와 같이 설계하였다. 
![image](https://github.com/ParansaikStudy/LDK-SpringBase/assets/91397068/cc958d93-90df-4fc2-badb-35047218a38d)

**Comment by Paransaik** [comment]
REST API는 `REST는 자원을 표현하고 상태를 전송하기 위한 아키텍처`로 URL을 통해 Server <-> Clent가 통신합니다.

REST API 설계의 의미는 C, R, U, D에 해당하는 URL을 작성하는 것을 의미하며 아래 사진은 폴더 구조로 보여지네요.

REST API를 이해한 뒤 REST API 설계가 필요해보입니다.

**Comment by dbzoseh2rl** [comment]
Rest Api설계 완료하였습니다!

**Comment by Paransaik** [comment]
저희는 크게 다른 기능이 없기 때문에 비교적 단순하게 url 이 구성되었는데,
프로젝트가 커짐에 따라 url도 복잡해지기 때문에 잘 나누셔야 합니다.

참고하세요!
